### ISSUE TITLE
PGN export

### ISSUE THREAD

**Issue by jiri132** [jiri132/ChessApp_V2#1]
### User story
> When clicking on Export PGN, I want it to export to a PGN that the user can import into Chess.com

### Tasks
- [x] Copy PGN to clipboard
- [x] Create PGN details
- [ ] Create a valid PGN

### Where do you need to be?
the svelte file [[here](https://github.com/jiri132/ChessApp_V2/blob/main/src/lib/ChessBoard/UI-Frameworks/displayMoves.svelte)](src/lib/ChessBoard/UI-Frameworks/displayMoves.svelte)
