### ISSUE TITLE
Rounds Battle

### ISSUE THREAD

**Issue by jiri132** [jiri132/ChessApp_V2#2]
### User  story
> When you are in the settings tab be able to set how many times they can play each other

### Todos
- [ ] Slider with rounds
- [ ] min 1 max 100
- [ ] save in an array of "rounds"
- [ ] display the wins / losses
