### ISSUE TITLE
User Names display

### ISSUE THREAD

**Issue by jiri132** [jiri132/ChessApp_V2#4]
### User story
> As normal chess see which color is which party 

### Todos
- [x] player / bot name 
- [x] above black & below white
- [ ] bot 1: always bottom
