### ISSUE TITLE
Alert Pop-ups

### ISSUE THREAD

**Issue by jiri132** [jiri132/ChessApp_V2#5]
### User story
> At this time it is hard to tell what happened when they stopped playing so make a pop-up to see what happened

### Todos
- [ ] create pop up component
- [ ] popup with details {outcome, quit | new}
- [ ] be able to view the board (quit)
- [ ] be able to restart the board with selected players form there (new)

**Comment by Jecanart** [comment]
Hello, can I help with this?

**Comment by jiri132** [comment]
hello @Jecanart 👋!

You can help me with this if you could fork the repo create a new branch and then make a pop-up message that will display who has won and by what for example!
 
I use the frontend framework svelte, to run the svelte Frontend you need to run the command: `npm run dev`


Kind regards,
JB

**Comment by Jecanart** [comment]
I have sent a PR, if there is something that needs to be changed just @ me 👍

**Comment by jiri132** [comment]
hey @Jecanart 👋 ,
I have checked out the PR, and it looks great! 

only downside is the styling but that could be another issue :D

kind regards,
JB
