### ISSUE TITLE
Bot development in app

### ISSUE THREAD

**Issue by jiri132** [jiri132/ChessApp_V2#8]
### User story
> When having an application be able to create a bot inside of it

### Todos
- [ ] text field for code
- [ ] send code to javascript script
- [ ] execute the script (hopefully)
