### ISSUE TITLE
Statistics display

### ISSUE THREAD

**Issue by jiri132** [jiri132/ChessApp_V2#9]
### User story
> When having the rounds, it is hard to see how much it was in win draw loss <bot1 - bot2>

### Todos 
- [ ] display bar
- [ ] coloring the bar 
- [ ] green : win , gray : draw, red : loss
- [ ] clicking on area shows the games that where being played
